print("Welcome to the Band Name Generator.")
city = input("What is the name of the city you grew up in? ")
print(city)
pet = input("What is the name of your pet? ")
print(pet)
print("Your band name could be", city + " " + pet)
